/**
 * Dodonaut Postgres schema (PRD §9.4).
 *
 * Tables:
 *  - users / sessions / accounts / verifications  → Better-Auth managed (created by `npx @better-auth/cli generate`)
 *  - merchants                                     → one per signed-up user; mirrors Dodo customer + Solana wallet
 *  - products                                      → mirror of merchant's Dodo products + Dodonaut config
 *  - endpoints                                     → one per "wrap" action (the x402 paywall config)
 *  - on_chain_receipts                             → one per detected SPL transfer
 *  - agent_wallets                                 → lazy-created per agent pubkey on first sighting
 *
 * IMPORTANT — Path A/B reconciliation (PRD §6, V2 risk):
 *  - merchants.dodo_agents_customer_id is pre-added even though Path A doesn't need it.
 *    If V2 fails (Dodo rejects arbitrary customer_id strings in /events), we populate
 *    this column on signup with a sentinel customer; ingestion uses it. Zero migration on Day 5.
 */

import {
  pgTable,
  uuid,
  text,
  bigint,
  timestamp,
  boolean,
  integer,
  jsonb,
  pgEnum,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

// ----- Better-Auth tables (will be regenerated by Better-Auth CLI; included here for FK) ----

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ----- Dodonaut domain tables ---------------------------------------------------------------

export const dodoEnvironment = pgEnum("dodo_environment", ["test_mode", "live_mode"]);
export const settlementAsset = pgEnum("settlement_asset", ["USDG", "USDC"]);
export const endpointMode = pgEnum("endpoint_mode", ["x402", "human", "both"]);
export const productType = pgEnum("product_type", ["one_time", "subscription", "usage"]);
export const invoiceStatus = pgEnum("invoice_status", [
  "pending",
  "settled",
  "expired",
  "refunded",
]);

export const merchants = pgTable(
  "merchants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    dodoCustomerId: text("dodo_customer_id").notNull(),
    /**
     * V2 Path B fallback (PRD §6): if Dodo /events rejects arbitrary customer_id strings,
     * we pre-create one sentinel customer per merchant and ingest all agent calls under it.
     * Populated on signup if Path B is active; null otherwise.
     */
    dodoAgentsCustomerId: text("dodo_agents_customer_id"),
    dodoApiKeyEncrypted: text("dodo_api_key_encrypted").notNull(),
    dodoWebhookKeyEncrypted: text("dodo_webhook_key_encrypted").notNull(),
    dodoEnvironment: dodoEnvironment("dodo_environment").notNull().default("test_mode"),
    solanaAddress: text("solana_address").notNull(),
    defaultSettlementAsset: settlementAsset("default_settlement_asset")
      .notNull()
      .default("USDG"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("merchants_slug_idx").on(t.slug),
    uniqueIndex("merchants_user_id_idx").on(t.userId),
    index("merchants_solana_address_idx").on(t.solanaAddress),
  ],
);

export const products = pgTable(
  "products",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    merchantId: uuid("merchant_id")
      .notNull()
      .references(() => merchants.id, { onDelete: "cascade" }),
    dodoProductId: text("dodo_product_id").notNull(),
    /** The Dodo Usage meter to bill against, when type='usage'. Optional otherwise. */
    dodoMeterId: text("dodo_meter_id"),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    type: productType("type").notNull(),
    /** USD price in 6-decimal base units (e.g., $0.05 = 50000). Mirrors Dodo product price. */
    priceUsdBaseUnits: bigint("price_usd_base_units", { mode: "bigint" }).notNull(),
    rawDodoProduct: jsonb("raw_dodo_product"),
    archived: boolean("archived").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("products_merchant_dodo_product_idx").on(t.merchantId, t.dodoProductId),
    index("products_merchant_id_idx").on(t.merchantId),
  ],
);

export const endpoints = pgTable(
  "endpoints",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    merchantId: uuid("merchant_id")
      .notNull()
      .references(() => merchants.id, { onDelete: "cascade" }),
    /** The merchant's actual upstream API the agent should reach after paying. */
    upstreamUrl: text("upstream_url").notNull(),
    /** Per-call price in USD base units. Defaults to product price; merchant can override. */
    priceUsdBaseUnits: bigint("price_usd_base_units", { mode: "bigint" }).notNull(),
    /** Subset of {USDG, USDC} the merchant accepts for this endpoint. USDG first if present. */
    acceptedAssets: text("accepted_assets")
      .array()
      .notNull()
      .default(["USDG", "USDC"]),
    description: text("description"),
    mode: endpointMode("mode").notNull().default("x402"),
    enabled: boolean("enabled").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("endpoints_merchant_id_idx").on(t.merchantId),
    index("endpoints_product_id_idx").on(t.productId),
  ],
);

export const onChainReceipts = pgTable(
  "on_chain_receipts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    endpointId: uuid("endpoint_id").references(() => endpoints.id, {
      onDelete: "set null",
    }),
    merchantId: uuid("merchant_id")
      .notNull()
      .references(() => merchants.id, { onDelete: "cascade" }),
    /** Solana transaction signature — globally unique, also used as Dodo events idempotency key. */
    signature: text("signature").notNull(),
    blockTime: timestamp("block_time", { withTimezone: true }).notNull(),
    agentWallet: text("agent_wallet").notNull(),
    amountBaseUnits: bigint("amount_base_units", { mode: "bigint" }).notNull(),
    asset: settlementAsset("asset").notNull(),
    network: text("network").notNull(),
    /** End-to-end latency from agent retry to upstream response. */
    endToEndLatencyMs: integer("end_to_end_latency_ms"),
    rawHeliusEvent: jsonb("raw_helius_event"),
    /** Populated once Dodo /events ingestion is confirmed. */
    dodoEventId: text("dodo_event_id"),
    dodoIngestedAt: timestamp("dodo_ingested_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("on_chain_receipts_signature_idx").on(t.signature),
    index("on_chain_receipts_merchant_id_idx").on(t.merchantId),
    index("on_chain_receipts_agent_wallet_idx").on(t.agentWallet),
    index("on_chain_receipts_endpoint_id_idx").on(t.endpointId),
  ],
);

export const agentWallets = pgTable("agent_wallets", {
  pubkey: text("pubkey").primaryKey(),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  callCount: integer("call_count").notNull().default(0),
  totalSpentUsdBaseUnits: bigint("total_spent_usd_base_units", { mode: "bigint" })
    .notNull()
    .default(0n),
});

// ----- Type helpers -----------------------------------------------------------------------

export type Merchant = typeof merchants.$inferSelect;
export type NewMerchant = typeof merchants.$inferInsert;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type Endpoint = typeof endpoints.$inferSelect;
export type NewEndpoint = typeof endpoints.$inferInsert;
export type OnChainReceipt = typeof onChainReceipts.$inferSelect;
export type NewOnChainReceipt = typeof onChainReceipts.$inferInsert;
export type AgentWallet = typeof agentWallets.$inferSelect;
export type NewAgentWallet = typeof agentWallets.$inferInsert;
